# anonymous users
anonymous_enable=NO

# allow user to log in
local_enable=YES

# listen IPv4
listen=YES
listen_ipv6=NO

# write permission
write_enable=YES

# set the home directory as root
chroot_local_user=YES
allow_writeable_chroot=YES

# set the root directory
local_root=/var/www/html

# passive mode configuration
pasv_enable=YES
pasv_address=0.0.0.0
pasv_min_port=21100
pasv_max_port=21110

# logging activity
xferlog_enable=YES

seccomp_sandbox=NO