daemon                          off;
user                            wp_user;
worker_processes                auto;

error_log                       /var/log/nginx/error.log warn;

events {
    worker_connections          1024;
}

http {

    ##
    # Basic Settings
    ##
    
    sendfile                    on; # avoids copying file to memory from disk before sending it
    access_log                  /var/log/nginx/access.log;
    keepalive_timeout           65;

    # --- File type definitions
    include                     /etc/nginx/mime.types;
    default_type                application/octet-stream;

    ##
    # SSL Settings
    ##

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    ##
    # Server block
    ##

    # Wordpress
    server {
        listen                  443 ssl;
        root                    /var/www/html;
        index                   index.php;
        server_name             ielmoudd.42.fr;
        client_max_body_size    32m;
        
        ssl_certificate     /run/secrets/nginx_crt;
        ssl_certificate_key /run/secrets/nginx_key;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }
        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }

    # Adminer
    server {
        listen                  500 ssl;
        server_name             ielmoudd.42.fr;

        ssl_certificate     /run/secrets/nginx_crt;
        ssl_certificate_key /run/secrets/nginx_key;

        location / {
            proxy_pass http://adminer:8080;

        }
    }

    # static site
    server {
        listen  600 ssl;
        
        ssl_certificate     /run/secrets/nginx_crt;
        ssl_certificate_key /run/secrets/nginx_key;

        server_name             ielmoudd.42.fr;

        location / {
            proxy_pass http://website:8000;

        }
    }

    # goaccess
    server {
        listen  700 ssl;
        server_name             ielmoudd.42.fr;

        ssl_certificate     /run/secrets/nginx_crt;
        ssl_certificate_key /run/secrets/nginx_key;

        root    /var/www/html;
        index   monitor.html;

        location / {
            try_files $uri /monitor.html;
        }


        location /ws {
            proxy_pass http://service:7890; 
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
        }
    }

}
